  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: book-service-deployment
    namespace: book-service-app
    labels:
      app: book-service-app
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: book-service-app
    template:
      metadata:
        labels:
          app: book-service-app
      spec:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: kubernetes.io/arch
                      operator: In
                      values:
                        - amd64
                        - arm64
        containers:
          - name: bookapi
            image: public.ecr.aws/o0j8b8u8/diss-a3:bookapi
            ports:
              - containerPort: 3000
            imagePullPolicy: IfNotPresent
        nodeSelector:
          kubernetes.io/os: linux