  apiVersion: v1
  kind: Service
  metadata:
    name: crm-service
    namespace: crm-service-app
    labels:
      app: crm-service-app
  spec:
    type: NodePort
    selector:
      app: crm-service-app
    ports:
      - protocol: TCP
        port: 3000
        targetPort: 3000