  apiVersion: v1
  kind: Service
  metadata:
    name: book-service
    namespace: book-service-app
    labels:
      app: book-service-app
  spec:
    type: NodePort
    selector:
      app: book-service-app
    ports:
      - protocol: TCP
        port: 3000
        targetPort: 3000