apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-bff-deployment
  namespace: book-service-app
  labels:
    app: book-bff-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-bff-app
  template:
    metadata:
      labels:
        app: book-bff-app
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
                      - arm64
      containers:
        - name: bookapi
          image: public.ecr.aws/o0j8b8u8/diss-a3:bookbff
          ports:
            - containerPort: 80
          imagePullPolicy: IfNotPresent
      nodeSelector:
        kubernetes.io/os: linux