  apiVersion: v1
  kind: Service
  metadata:
    name: customer-service
    namespace: customer-service-app
    labels:
      app: customer-service-app
  spec:
    type: NodePort
    selector:
      app: customer-service-app
    ports:
      - protocol: TCP
        port: 80
        targetPort: 80