  apiVersion: v1
  kind: Service
  metadata:
    name: customer-bff
    namespace: customer-service-app
    labels:
      app: customer-bff-app
  spec:
    type: LoadBalancer
    selector:
      app: customer-bff-app
    ports:
      - protocol: TCP
        port: 80
        targetPort: 80